# 端口
server:
  port: 8086
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: zuul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: ROOT

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: localhost
  client:
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: rabbit
    api-b:
      path: /api-b/**
      service-id: feign
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
